<?php

namespace Cocina\ComprasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlmacenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlmacenesRepository extends EntityRepository
{
	public function queryTodosLosAlmacenes()
	{
		$em=$this->getEntityManager();
		$consulta=$em->createQuery('
				SELECT a 
				FROM ComprasBundle:Almacenes a 
				ORDER BY a.nombreAlmacen
				');
		return $consulta;
	}
	
	public function findTodosLosAlmacenes()
	{
		return $this->queryTodosLosAlmacenes();
	}
	
	
}
