<?php

namespace Cocina\ComprasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Pedidos_detalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pedidos_detalleRepository extends EntityRepository
{
	public function findPedidosDetallePorIdPedido($id)
	{
		$em=$this->getEntityManager();
		$consulta=$em->createQuery('
				SELECT p
				FROM ComprasBundle:Pedidos_detalle p
				WHERE p.idPedido = :id
				ORDER BY p.cantidadPedida ASC
				');
		$consulta->setParameter('id', $id);
		return $consulta;
	}
}
