<?php

namespace Cocina\ComprasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PedidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidosRepository extends EntityRepository
{
	public function findPedidosProcesados()
	{
		$em=$this->getEntityManager();
		$consulta=$em->createQuery('
				SELECT p, o
				FROM ComprasBundle:Pedidos p
				JOIN p.idProveedor o
				WHERE p.entregado = :entregado
				ORDER BY p.fechaPedido ASC
				');
		$consulta->setParameter('entregado', 1);
		return $consulta;
	}
	
	public function findPedidosPendientes()
	{
		$em=$this->getEntityManager();
		$consulta=$em->createQuery('
				SELECT p, o
				FROM ComprasBundle:Pedidos p
				JOIN p.idProveedor o
				WHERE p.entregado = :entregado
				ORDER BY p.fechaPedido ASC
				');
		$consulta->setParameter('entregado', 0);
		return $consulta;
	}
}
