calidad:
    resource: "@CalidadBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

nutricion:
    resource: "@NutricionBundle/Resources/config/routing.yml"
    prefix:   /

trazabilidad:
    resource: "@TrazabilidadBundle/Resources/config/routing.yml"
    prefix:   /

diseno:
    resource: "@DisenoBundle/Resources/config/routing.yml"
    prefix:   /

compras:
    resource: "@ComprasBundle/Resources/config/routing.yml"
    prefix:   /



    
portada:
    path: /home/
    defaults: { _controller:ComprasBundle:Default:portada }
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin    
        