security:

    firewalls:
        frontend:
            pattern: ^/*
            anonymous:    ~
            provider:  usuarios
            #http_basic: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check 
                default_target_path: /home/
                always_use_default_target_path: true             
            logout:
                path:       usuario_logout
                target:     /home
            remember_me:
                key:    1234
                lifetime:    3600
                    
                
    access_control:
        - {path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/*, roles: ROLE_USUARIO}
        
    providers:
        usuarios:
            entity: { class: Cocina\UsuarioBundle\Entity\Usuarios, property: nick }
            #memory:
               # users:
                    #- { name: admin, password: 1234, roles: ROLE_USUARIO }   
            
    encoders:
            Cocina\UsuarioBundle\Entity\Usuarios:    plaintext
            Symfony\Component\Security\Core\User\User: plaintext
