services:
#    app.form.type.pedidos:
#        class: Cocina\ComprasBundle\Form\Pedidos_detalleType
#        arguments: ["@doctrine.orm.entity_manager"]
#        tags:
#            - { name: form.type, alias:fooShortlist }